"""Executable package entry point for ``python -m pollypm``."""

from __future__ import annotations

import sys
from pathlib import Path


_COCKPIT_PANE_HELP_FLAGS = frozenset({"--help", "-h"})
_CLEAR_SCREEN = "\x1b[2J\x1b[H"


def _parse_cockpit_pane_options(
    argv: list[str],
) -> tuple[Path | None, str | None] | None:
    """Parse the simple ``cockpit-pane`` shape generated by the router."""
    target: str | None = None
    project: str | None = None
    config_path: Path | None = None
    index = 2
    while index < len(argv):
        token = argv[index]
        if token in {"--project", "-p", "--config", "--task"}:
            value_index = index + 1
            if value_index >= len(argv) or argv[value_index].startswith("-"):
                return None
            value = argv[value_index]
            if token in {"--project", "-p"}:
                project = value
            elif token == "--config":
                config_path = Path(value)
            index += 2
            continue
        if token.startswith("-"):
            return None
        if target is not None:
            return None
        target = token
        index += 1
    return config_path, project or target


def _run_cockpit_pane_fast(argv: list[str]) -> bool:
    """Launch hot right-pane apps without importing the full root CLI.

    ``CockpitRouter`` spawns panes with ``python -m pollypm cockpit-pane ...``.
    Importing :mod:`pollypm.cli` first loads every top-level command family
    before the pane-specific command can import its Textual app. The Inbox
    cold path is budgeted from keystroke to first paint, so avoid that root CLI
    import for the pane launches the cockpit itself generates. Help and any
    unfamiliar shape fall back to the Typer command below.
    """
    if len(argv) < 2 or argv[0] != "cockpit-pane":
        return False
    if any(token in _COCKPIT_PANE_HELP_FLAGS for token in argv[1:]):
        return False
    kind = argv[1]
    if kind != "inbox":
        return False

    parsed = _parse_cockpit_pane_options(argv)
    if parsed is None:
        return False
    config_path, project = parsed

    from pollypm.cli_features.ui import (
        _enforce_migration_gate,
        _install_cockpit_debug_log_handler,
    )
    from pollypm.config import DEFAULT_CONFIG_PATH

    resolved_config_path = config_path or Path(DEFAULT_CONFIG_PATH)
    _enforce_migration_gate(resolved_config_path)
    _install_cockpit_debug_log_handler(resolved_config_path)
    _paint_inbox_loading_placeholder()

    from pollypm.cockpit_ui import PollyInboxApp

    PollyInboxApp(resolved_config_path, initial_project=project).run(mouse=True)
    return True


def _paint_inbox_loading_placeholder() -> None:
    """Show an immediate frame while Textual builds and loads the inbox.

    The cockpit's Home -> Inbox budget is measured from keypress to first
    visible pane content. ``PollyInboxApp.on_mount`` still performs the real
    inbox read before its first Textual frame, so print a minimal truthful
    loading frame before importing/rendering the heavy app work.
    """
    try:
        sys.stdout.write(
            f"{_CLEAR_SCREEN}"
            "Inbox\n\n"
            "Loading action needed items..."
        )
        sys.stdout.flush()
    except Exception:  # noqa: BLE001 - placeholder must never block launch
        pass


def main() -> None:
    if _run_cockpit_pane_fast(sys.argv[1:]):
        return
    from pollypm.cli import app

    app()


if __name__ == "__main__":
    main()
