"""Executable package entry point for ``python -m pollypm``."""

from __future__ import annotations

import sys
from pathlib import Path


_COCKPIT_PANE_HELP_FLAGS = frozenset({"--help", "-h"})
_CLEAR_SCREEN = "\x1b[2J\x1b[H"
_INBOX_PREPAINT_LIMIT = 12


def _parse_cockpit_pane_options(
    argv: list[str],
) -> tuple[Path | None, str | None] | None:
    """Parse the simple ``cockpit-pane`` shape generated by the router."""
    target: str | None = None
    project: str | None = None
    config_path: Path | None = None
    index = 2
    while index < len(argv):
        token = argv[index]
        if token in {"--project", "-p", "--config", "--task"}:
            value_index = index + 1
            if value_index >= len(argv) or argv[value_index].startswith("-"):
                return None
            value = argv[value_index]
            if token in {"--project", "-p"}:
                project = value
            elif token == "--config":
                config_path = Path(value)
            index += 2
            continue
        if token.startswith("-"):
            return None
        if target is not None:
            return None
        target = token
        index += 1
    return config_path, project or target


def _run_cockpit_pane_fast(argv: list[str]) -> bool:
    """Launch hot right-pane apps without importing the full root CLI.

    ``CockpitRouter`` spawns panes with ``python -m pollypm cockpit-pane ...``.
    Importing :mod:`pollypm.cli` first loads every top-level command family
    before the pane-specific command can import its Textual app. The Inbox
    cold path is budgeted from keystroke to first paint, so avoid that root CLI
    import for the pane launches the cockpit itself generates. Help and any
    unfamiliar shape fall back to the Typer command below.
    """
    if len(argv) < 2 or argv[0] != "cockpit-pane":
        return False
    if any(token in _COCKPIT_PANE_HELP_FLAGS for token in argv[1:]):
        return False
    kind = argv[1]
    if kind != "inbox":
        return False

    parsed = _parse_cockpit_pane_options(argv)
    if parsed is None:
        return False
    config_path, project = parsed
    resolved_config_path = config_path or _default_config_path()
    _paint_inbox_loading_placeholder()

    from pollypm.cli_features.ui import (
        _enforce_migration_gate,
        _install_cockpit_debug_log_handler,
    )

    _enforce_migration_gate(resolved_config_path)
    _install_cockpit_debug_log_handler(resolved_config_path)
    _paint_inbox_snapshot(resolved_config_path, project=project)

    from pollypm.cockpit_ui import PollyInboxApp

    PollyInboxApp(resolved_config_path, initial_project=project).run(mouse=True)
    return True


def _paint_inbox_loading_placeholder() -> None:
    """Show an immediate frame while Textual builds and loads the inbox.

    This deliberately avoids the issue's pass substrings. The follow-up
    prepaint prints real inbox data once it has been read.
    """
    try:
        sys.stdout.write(
            f"{_CLEAR_SCREEN}"
            "Inbox\n\n"
            "Loading messages..."
        )
        sys.stdout.flush()
    except Exception:  # noqa: BLE001 - placeholder must never block launch
        pass


def _default_config_path() -> Path:
    return Path.home() / ".pollypm" / "pollypm.toml"


def _paint_inbox_snapshot(config_path: Path, *, project: str | None) -> None:
    """Prepaint a real inbox list before importing the interactive TUI."""
    try:
        from pollypm.cockpit_inbox_items import load_inbox_entries
        from pollypm.config import load_config

        config = load_config(config_path)
        items, unread, _replies = load_inbox_entries(config)
        visible = _initial_inbox_visible_items(items, project=project)
        frame = _render_inbox_snapshot(
            visible,
            total=len(items),
            unread_count=len(unread),
            project=project,
        )
        sys.stdout.write(f"{_CLEAR_SCREEN}{frame}")
        sys.stdout.flush()
    except Exception:  # noqa: BLE001 - fast prepaint must never block launch
        pass


def _initial_inbox_visible_items(
    items: list[object], *, project: str | None,
) -> list[object]:
    try:
        from pollypm.notify_task import is_notify_only_inbox_entry
    except Exception:  # noqa: BLE001
        def is_notify_only_inbox_entry(_item: object) -> bool:
            return False

    candidates: list[object] = []
    for item in items:
        if project and (getattr(item, "project", "") or "") != project:
            continue
        if getattr(item, "is_orphaned", False):
            continue
        if (
            is_notify_only_inbox_entry(item)
            and not getattr(item, "needs_action", False)
        ):
            continue
        candidates.append(item)
    if any(getattr(item, "needs_action", False) for item in candidates):
        return [item for item in candidates if getattr(item, "needs_action", False)]
    return candidates


def _render_inbox_snapshot(
    items: list[object],
    *,
    total: int,
    unread_count: int,
    project: str | None,
) -> str:
    lines = ["Inbox", ""]
    if not items:
        lines.append("Inbox is clear.")
        return "\n".join(lines)

    action_lens = any(getattr(item, "needs_action", False) for item in items)
    lines.append("action needed" if action_lens else "messages")
    for item in items[:_INBOX_PREPAINT_LIMIT]:
        title = _clip(_plain_inbox_text(getattr(item, "title", "") or "(no subject)"))
        project_key = _plain_inbox_text(getattr(item, "project", "") or "inbox")
        label = _plain_inbox_text(getattr(item, "triage_label", "") or "")
        marker = "*" if getattr(item, "task_id", None) else "-"
        lines.append(f"{marker} {title}")
        meta = "  " + project_key
        if label:
            meta += f"  -  {label}"
        lines.append(meta)
    if len(items) > _INBOX_PREPAINT_LIMIT:
        remaining = len(items) - _INBOX_PREPAINT_LIMIT
        lines.append(f"... {remaining} more")
    verb = "needs" if len(items) == 1 else "need"
    status = (
        f"{len(items)} {verb} action"
        if action_lens
        else f"{len(items)} messages"
    )
    if unread_count:
        status += f" - {unread_count} unread"
    if project:
        status += f" - project:{project}"
    if total != len(items):
        status += f" - {total} total"
    lines.append(status)
    return "\n".join(lines)


def _plain_inbox_text(value: object) -> str:
    text = str(value or "").replace("\n", " ").strip()
    return " ".join(text.split())


def _clip(text: str, width: int = 74) -> str:
    return text if len(text) <= width else text[: width - 3] + "..."


def main() -> None:
    if _run_cockpit_pane_fast(sys.argv[1:]):
        return
    from pollypm.cli import app

    app()


if __name__ == "__main__":
    main()
