"""Agentic plain-English summaries for task review handoffs.

Contract:
- Inputs: hydrated work-service tasks plus optional rejection-feedback text.
- Outputs: ``plain_summary`` context entries written through the work service.
- Side effects: invokes PollyPM's background LLM runner and appends task
  context; never mutates task state.
- Invariants: review wording is generated by an LLM, not rule-specific
  interpretation, and the generated text must not tell users to run ``pm``
  commands.
"""

from __future__ import annotations

import logging
import os
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable

from pollypm.work.models import Decision, FlowNodeExecution, NodeType, Task, WorkStatus

logger = logging.getLogger(__name__)

PLAIN_SUMMARY_ENTRY_TYPE = "plain_summary"
REVIEW_SUMMARY_ACTOR = "review_summary"

_DISABLE_ENV = "POLLYPM_DISABLE_AGENTIC_REVIEW_SUMMARIES"
_FORBIDDEN_CLI_RE = re.compile(r"\bpm\s+(?:task|issue|flow|up|cockpit|worker|alert)\b", re.I)

review_summary_invocation: Callable[[str], str | None] | None = None


@dataclass(slots=True)
class ReviewSummaryBackfillResult:
    task_id: str
    status: str
    outcome: str
    message: str = ""


def _status_value(value: object) -> str:
    return str(getattr(value, "value", value) or "").strip().lower()


def _decision_value(value: object) -> str:
    return str(getattr(value, "value", value) or "").strip().lower()


def _plain_line(value: object) -> str:
    text = str(value or "").strip()
    if not text:
        return ""
    return " ".join(part.strip() for part in text.splitlines() if part.strip())


def _clip_plain_text(text: str, *, limit: int = 1800) -> str:
    clean = _plain_line(text)
    if len(clean) <= limit:
        return clean
    cut = clean.rfind(" ", 0, limit)
    if cut <= 0 or cut < limit - 80:
        cut = limit - 1
    return clean[:cut].rstrip() + "..."


def _existing_plain_summary(task: Task) -> str | None:
    entries = [
        entry
        for entry in list(getattr(task, "context", None) or [])
        if getattr(entry, "entry_type", "") == PLAIN_SUMMARY_ENTRY_TYPE
    ]
    entries.sort(key=lambda entry: _timestamp_key(getattr(entry, "timestamp", None)), reverse=True)
    for entry in entries:
        text = str(getattr(entry, "text", "") or "").strip()
        if text:
            return text
    return None


def _timestamp_key(value: object | None) -> float:
    if value is None:
        return 0.0
    if isinstance(value, datetime):
        stamp = value
    else:
        try:
            stamp = datetime.fromisoformat(str(value))
        except ValueError:
            return 0.0
    if stamp.tzinfo is None:
        stamp = stamp.replace(tzinfo=timezone.utc)
    return stamp.timestamp()


def _latest_rejection_reason(task: Task) -> str:
    for execution in reversed(list(getattr(task, "executions", None) or [])):
        if _decision_value(getattr(execution, "decision", None)) != Decision.REJECTED.value:
            continue
        reason = str(getattr(execution, "decision_reason", "") or "").strip()
        if reason:
            return reason
    for transition in reversed(list(getattr(task, "transitions", None) or [])):
        actor = str(getattr(transition, "actor", "") or "").strip().lower()
        reason = str(getattr(transition, "reason", "") or "").strip()
        if actor in {"reviewer", "russell", "polly", "user"} and reason:
            return reason
    return ""


def _latest_completed_work_execution(task: Task) -> FlowNodeExecution | None:
    for execution in reversed(list(getattr(task, "executions", None) or [])):
        output = getattr(execution, "work_output", None)
        if output is not None and str(getattr(output, "summary", "") or "").strip():
            return execution
    return None


def _is_reviewish_task(service, task: Task) -> bool:
    status = _status_value(getattr(task, "work_status", ""))
    if status == WorkStatus.REVIEW.value:
        return True
    if status != WorkStatus.ON_HOLD.value:
        return False
    try:
        _flow, node = service._get_current_flow_node(task)
    except Exception:  # noqa: BLE001
        return False
    return getattr(node, "type", None) == NodeType.REVIEW


def _work_output_context(task: Task) -> str:
    execution = _latest_completed_work_execution(task)
    if execution is None:
        return "No completed worker output was attached to this task."
    output = getattr(execution, "work_output", None)
    lines = [
        f"Node: {getattr(execution, 'node_id', '') or 'unknown'}",
        f"Summary: {_clip_plain_text(getattr(output, 'summary', '') or '', limit=2400)}",
    ]
    artifacts = list(getattr(output, "artifacts", None) or [])
    if artifacts:
        lines.append("Artifacts:")
        for artifact in artifacts[:8]:
            kind = getattr(getattr(artifact, "kind", None), "value", None) or getattr(
                artifact, "kind", None,
            )
            bits = [str(kind or "artifact")]
            description = getattr(artifact, "description", None)
            if description:
                bits.append(_clip_plain_text(str(description), limit=220))
            ref = getattr(artifact, "ref", None)
            if ref:
                bits.append(f"ref={ref}")
            path = getattr(artifact, "path", None)
            if path:
                bits.append(f"path={path}")
            external_ref = getattr(artifact, "external_ref", None)
            if external_ref:
                bits.append(f"external={external_ref}")
            lines.append(f"- {' | '.join(bits)}")
    return "\n".join(lines)


def _prompt_for_review_summary(
    task: Task,
    *,
    rejection_feedback_text: str | None = None,
) -> str:
    rejection_text = (
        _latest_rejection_reason(task)
        or str(rejection_feedback_text or "").strip()
        or "No earlier rejection feedback was found."
    )
    return f"""You write the top "In plain English" message for PollyPM's task review UI.

The person reading it is deciding whether to approve or reject the current task state. Write the message they need at the top of the review screen.

Rules:
- Return only the user-facing message.
- Write in clear, plain English. No workflow jargon unless it is part of a requirement name.
- Start with what the user is being asked to approve.
- If multiple deviations, tradeoffs, or scope changes are being approved, number them.
- Say what approval means and what rejection should ask for.
- Avoid double negatives and legalistic phrasing.
- Do not tell the user to run pm commands or any CLI commands.
- Keep it short: 2 to 6 lines.

Good shape for scope-change reviews:
You're being asked to approve two deviations from the original plan.
1. <decision one in plain English>
2. <decision two in plain English>
Approve if those tradeoffs are acceptable for this version; reject if either requirement still needs to be met now.

Task:
- ID: {task.task_id}
- Title: {_clip_plain_text(getattr(task, "title", ""), limit=400)}
- Status: {_status_value(getattr(task, "work_status", ""))}
- Current node: {getattr(task, "current_node_id", None) or "unknown"}
- Flow: {getattr(task, "flow_template_id", "") or "unknown"}
- Description: {_clip_plain_text(getattr(task, "description", ""), limit=1200)}
- Acceptance criteria: {_clip_plain_text(getattr(task, "acceptance_criteria", "") or "", limit=1200) or "None provided."}
- Constraints: {_clip_plain_text(getattr(task, "constraints", "") or "", limit=1200) or "None provided."}

Latest worker submission:
{_work_output_context(task)}

Earlier rejection/reviewer feedback:
{_clip_plain_text(rejection_text, limit=2600)}
"""


def _sanitize_summary(text: str | None) -> str | None:
    if text is None:
        return None
    clean = text.strip()
    if not clean:
        return None
    if clean.startswith("```"):
        lines = [
            line
            for line in clean.splitlines()
            if not line.strip().startswith("```")
        ]
        clean = "\n".join(lines).strip()
    clean = re.sub(r"^\s*(?:In plain English|Summary)\s*:\s*", "", clean, flags=re.I)
    lines = [line.rstrip() for line in clean.splitlines() if line.strip()]
    clean = "\n".join(lines[:8]).strip()
    if not clean:
        return None
    if _FORBIDDEN_CLI_RE.search(clean):
        logger.warning("review summary rejected because it included a pm CLI instruction")
        return None
    if len(clean) > 1400:
        clean = _clip_plain_text(clean, limit=1400)
    return clean


def generate_review_plain_summary(
    task: Task,
    *,
    rejection_feedback_text: str | None = None,
    config_path: Path | None = None,
) -> str | None:
    """Ask the LLM to write the review summary for one task."""

    if os.environ.get(_DISABLE_ENV):
        return None
    prompt = _prompt_for_review_summary(
        task,
        rejection_feedback_text=rejection_feedback_text,
    )
    try:
        if review_summary_invocation is not None:
            raw = review_summary_invocation(prompt)
        else:
            from pollypm.llm_runner import DEFAULT_CONFIG_PATH, run_haiku

            raw = run_haiku(prompt, config_path=config_path or DEFAULT_CONFIG_PATH)
    except Exception as exc:  # noqa: BLE001
        logger.warning("review summary generation failed for %s: %s", task.task_id, exc)
        return None
    return _sanitize_summary(raw)


def store_review_plain_summary(
    service,
    task_id: str,
    *,
    actor: str = REVIEW_SUMMARY_ACTOR,
    force: bool = False,
    rejection_feedback_text: str | None = None,
    config_path: Path | None = None,
) -> str | None:
    """Generate and persist a review ``plain_summary`` for ``task_id``."""

    task = service.get(task_id)
    if not _is_reviewish_task(service, task):
        return None
    if not force and _existing_plain_summary(task):
        return _existing_plain_summary(task)
    summary = generate_review_plain_summary(
        task,
        rejection_feedback_text=rejection_feedback_text,
        config_path=config_path,
    )
    if not summary:
        return None
    service.add_context(
        task_id,
        actor,
        summary,
        entry_type=PLAIN_SUMMARY_ENTRY_TYPE,
    )
    return summary


def backfill_review_plain_summaries(
    service,
    *,
    project: str | None = None,
    task_id: str | None = None,
    force: bool = False,
    limit: int | None = None,
    config_path: Path | None = None,
) -> list[ReviewSummaryBackfillResult]:
    """Generate missing review summaries for existing review/on-hold tasks."""

    try:
        from pollypm.rejection_feedback import unread_rejection_feedback

        feedback_by_task = unread_rejection_feedback(service, project=project)
    except Exception:  # noqa: BLE001
        feedback_by_task = {}

    if task_id:
        candidates = [service.get(task_id)]
    else:
        candidates = list(service.list_tasks(project=project))

    results: list[ReviewSummaryBackfillResult] = []
    generated = 0
    for candidate in candidates:
        full = service.get(candidate.task_id)
        status = _status_value(getattr(full, "work_status", ""))
        if not _is_reviewish_task(service, full):
            results.append(ReviewSummaryBackfillResult(full.task_id, status, "skipped", "not in review"))
            continue
        if limit is not None and generated >= limit:
            results.append(ReviewSummaryBackfillResult(full.task_id, status, "skipped", "limit reached"))
            continue
        existing = _existing_plain_summary(full)
        if existing and not force:
            results.append(ReviewSummaryBackfillResult(full.task_id, status, "skipped", "already has plain_summary"))
            continue
        feedback = feedback_by_task.get(full.task_id)
        rejection_text = getattr(feedback, "full_text", None) if feedback is not None else None
        summary = store_review_plain_summary(
            service,
            full.task_id,
            force=force,
            rejection_feedback_text=rejection_text,
            config_path=config_path,
        )
        if summary:
            generated += 1
            results.append(ReviewSummaryBackfillResult(full.task_id, status, "generated"))
        else:
            results.append(ReviewSummaryBackfillResult(full.task_id, status, "failed", "generation returned no summary"))
    return results
